### PR TITLE
Fix using Rust types in owned and borrowed contexts

### LINKED ISSUE #513: gen-guest-rust: cannot reuse shared records between import and export interfaces
The following wit file:

```
interface types {
    record a {
        b: string    
    }
}

interface foo {
    use self.types.{a}

    x: func(param: a)
}

interface bar {
    use self.types.{a}

    x: func(param: a)
    y: func() -> a
}

default world demo {
    import foo: self.foo
    export bar: self.bar
}
```

Fails to compile with the following error:

```rust
error[E0422]: cannot find struct, variant or union type `AParam` in this scope
 --> src/lib.rs:3:1
  |
3 | / wit_bindgen::generate!({
4 | |     world: "demo",
5 | | });
  | |__^ not found in this scope
  |
  = help: consider importing this struct:
          crate::types::AParam
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0412]: cannot find type `A` in module `super::types`
 --> src/lib.rs:3:1
  |
3 | / wit_bindgen::generate!({
4 | |     world: "demo",
5 | | });
  | |__^ not found in `super::types`
  |
  = help: consider importing this type alias:
          crate::foo::A
  = note: this error originates in the macro `wit_bindgen::generate` (in Nightly builds, run with -Z macro-backtrace for more info)
  ```
My findings:

The generated Rust type for `record a` gets split into two types and looks like this:

```rust
pub mod types {
    pub struct AParam<'a> {
        pub b: &'a str,
    }
    ...
    pub struct AResult {
        pub b: wit_bindgen::rt::string::String,
    }
    ...
}
```

However, The `bar` module attempts to import `record a` as `super::types::A;`:

```rust
pub mod bar {
    pub type A = super::types::A;
    ...
}
```

Conditions to encounter this error:

- one `import` interface uses a record (with a non-primitive field) as a function parameter
- an `export` interface uses the same record as either parameter or return type

Tested with:

- v0.3.0
- commit: 462527127f0d9de935f01e298a7e1c975e124a62

### PR DESCRIPTION
**Pull request by alexcrichton**
This pulls in type analysis code from Wasmtime which has a more modern notion of param/result as owned/borrowed and additionally removes the need for a `default_param_mode` which caused #513 in the first place.

Closes #513

### CODE REVIEW

**Comment by Mossaka** [comment]
I have already told Joel about the macos CI failure on maven. Feel free to merge it!

File: crates/gen-guest-c/src/lib.rs [hunk 1]
```diff
@@ -1457,6 +1462,9 @@ impl InterfaceGenerator<'_> {
                 self.src.h_helpers(&self.gen.world.to_snake_case());
                 self.src.h_helpers("_");
             }
+            Type::Id(id) => {
```
Comment (Mossaka) [inline crates/gen-guest-c/src/lib.rs:1465]: will this change the behavior of option flattening?

**Review by Mossaka — APPROVED** [review]
lgtm!

File: crates/gen-guest-c/src/lib.rs (hunk 1 above)
Comment (alexcrichton) [reply crates/gen-guest-c/src/lib.rs:1465]: Unfortunately no, this was just to fix some compile issues that cropped up with the new test case.
